import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Learnex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} debug-screens`}>
        <Navbar />
        <div className="px-4 sm:px-20 xl:px-32">
          <div className="h-20 lg:h-36"></div>
          {children}
        </div>
      </body>
    </html>
  );
}
